#!/usr/bin/env node
/**
 * Inlines content/writing/*.md into a TypeScript module.
 *
 * The site is deployed to Cloudflare Workers, which has no filesystem. Reading
 * the markdown with fs worked during the build but threw (or, worse, silently
 * returned nothing) whenever the Worker rendered a page at runtime. Baking the
 * files into the bundle removes that whole class of failure: the same data is
 * available at build time and at request time.
 *
 * Runs from next.config.ts on every build and dev start. The output is
 * committed so a fresh checkout, CI, and the test suite all work without
 * having to run this first.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const postsDir = join(root, "content", "writing");
const outFile = join(root, "src", "lib", "posts.data.ts");

export function generatePosts() {
  const entries = existsSync(postsDir)
    ? readdirSync(postsDir)
        .filter((name) => name.endsWith(".md"))
        .sort()
        .map((name) => ({
          slug: name.replace(/\.md$/, ""),
          raw: readFileSync(join(postsDir, name), "utf8"),
        }))
    : [];

  const body = `// Generated by scripts/generate-posts.mjs — do not edit.
// Source of truth is content/writing/*.md; this file exists so the markdown is
// bundled rather than read from a filesystem the Workers runtime doesn't have.

export interface RawPost {
  slug: string;
  raw: string;
}

export const RAW_POSTS: RawPost[] = ${JSON.stringify(entries, null, 2)};
`;

  mkdirSync(dirname(outFile), { recursive: true });

  // Avoid rewriting an identical file — a no-op write during `next dev` would
  // retrigger the watcher and loop.
  const current = existsSync(outFile) ? readFileSync(outFile, "utf8") : "";
  if (current !== body) writeFileSync(outFile, body);

  return entries.length;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const count = generatePosts();
  console.log(`Inlined ${count} post${count === 1 ? "" : "s"} into src/lib/posts.data.ts`);
}
